/** Irodori-TTS の感情・非言語の絵文字（セリフの前に付けると、その調子で読まれる）。広告で使いやすいものだけ */
export const IRODORI_EMOJI: { emoji: string; label: string }[] = [
  { emoji: '😆', label: '喜び' },
  { emoji: '😊', label: '楽しげ' },
  { emoji: '😲', label: '驚き' },
  { emoji: '😮', label: '息をのむ' },
  { emoji: '🤔', label: '疑問' },
  { emoji: '😟', label: '心配' },
  { emoji: '😰', label: '慌てる' },
  { emoji: '🥺', label: '震え声' },
  { emoji: '😭', label: '泣き声' },
  { emoji: '😠', label: '不満' },
  { emoji: '🙄', label: '呆れ' },
  { emoji: '😌', label: '安堵' },
  { emoji: '😎', label: '得意げ' },
  { emoji: '💪', label: '力強く' },
  { emoji: '💥', label: '勢いよく' },
  { emoji: '🫶', label: '優しく' },
  { emoji: '🫣', label: '照れ' },
  { emoji: '🤭', label: '笑い' },
  { emoji: '⏩', label: '早口' },
  { emoji: '🐢', label: 'ゆっくり' },
  { emoji: '📖', label: '朗読' },
];
